# -*- coding: utf-8 -*-
"""Untitled17 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dUsPXuKg205jbN6KWmTMhuiKHH1RJgcC
"""

!pip install numpy pandas pyarrow
!pip install transformers torch faiss-cpu tqdm scikit-learn ipywidgets networkx
!pip install spacy thinc==8.2.5 blis==0.7.11
!pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz
!pip install scispacy

# 2️⃣ Imports
import re, os, pickle, numpy as np
from pathlib import Path
from tqdm import tqdm
import torch, faiss
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModel, AutoModelForSeq2SeqLM
import ipywidgets as widgets
from IPython.display import display, clear_output
import spacy
import networkx as nx

# 3️⃣ Global Settings
BASE_DIR = Path("/content")
INDEX_DIR = BASE_DIR / "faiss_index"
INDEX_DIR.mkdir(exist_ok=True)

INDEX_PATH = INDEX_DIR / "pubmed.index"
META_PATH = INDEX_DIR / "metadata.csv"
EMBED_CACHE_PATH = INDEX_DIR / "embeddings_cache.pkl"

EMBED_DIM = 768
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 16

MAX_CE_LENGTH = 512
MAX_LLM_INPUT_TOKENS = 1024
MAX_LLM_OUTPUT_TOKENS = 512

# 4️⃣ Load SciSpacy model for Entity Extraction
nlp = spacy.load("en_core_sci_sm")

# 5️⃣ Load BioBERT encoder
print("🔹 Loading BioBERT encoder...")
biobert_tokenizer = AutoTokenizer.from_pretrained("dmis-lab/biobert-base-cased-v1.1")
biobert_model = AutoModel.from_pretrained("dmis-lab/biobert-base-cased-v1.1").to(DEVICE)
biobert_model.eval()

def encode_text_batch(texts):
    embeddings = []
    for i in range(0, len(texts), BATCH_SIZE):
        batch = texts[i:i+BATCH_SIZE]
        tokens = biobert_tokenizer(batch, return_tensors="pt", truncation=True,
                                   padding=True, max_length=512).to(DEVICE)
        with torch.no_grad():
            outputs = biobert_model(**tokens)
            batch_emb = outputs.last_hidden_state.mean(dim=1)
            embeddings.append(batch_emb.cpu().numpy().astype("float32"))
        del tokens, outputs, batch_emb
        torch.cuda.empty_cache()
    return np.vstack(embeddings)

# 6️⃣ Text preprocessing
ABBREVIATIONS = {"mi":"myocardial infarction","bp":"blood pressure","dm":"diabetes mellitus",
                 "copd":"chronic obstructive pulmonary disease","cvd":"cardiovascular disease","htn":"hypertension"}

def clean_text(text:str):
    text = re.sub(r"\[[0-9]+\]", " ", text)
    text = re.sub(r"\([0-9]{4}\)", " ", text)
    text = re.sub(r"[^a-zA-Z0-9.,;:%()\- ]", " ", text)
    return re.sub(r"\s+"," ", text).strip()

def expand_abbreviations(text:str):
    return " ".join(ABBREVIATIONS.get(w.lower(), w) for w in text.split())

def sentence_split(text:str): return re.split(r'(?<=[.!?])\s+', text)

def chunk_sentences(text:str, max_words=180):
    sentences = sentence_split(text)
    chunks, sentence_map, current, count = [], [], [], 0
    for sent in sentences:
        words = sent.split()
        if count + len(words) > max_words and current:
            chunks.append(" ".join(current))
            sentence_map.append(current)
            current, count = [], 0
        current.append(sent)
        count += len(words)
    if current:
        chunks.append(" ".join(current))
        sentence_map.append(current)
    return chunks, sentence_map

def preprocess_document(text:str):
    return chunk_sentences(expand_abbreviations(clean_text(text)))

def preprocess_query(text:str):
    return expand_abbreviations(clean_text(text))

def is_valid_chunk(text:str, min_words=25):
    return len(text.split())>=min_words

# 7️⃣ Load Dataset & Build FAISS Index (Optimized & Cached)
print("📥 Loading PubMed dataset...")
dataset = load_dataset("slinusc/PubMedAbstractsSubset", split="train[:1000]")
print("✅ Dataset loaded")

index = faiss.IndexFlatL2(EMBED_DIM)
metadata, sentence_maps = [], []

BATCH_SIZE = 50  # تعداد chunk هایی که یکجا encode میشن

if os.path.exists(EMBED_CACHE_PATH):
    print("📂 Loading cached embeddings...")
    with open(EMBED_CACHE_PATH, "rb") as f:
        embeddings = pickle.load(f)

    for item in tqdm(dataset, desc="Processing metadata from dataset"):
        pmid = int(item["PMID"])
        raw_text = f"{item['title']} {item['abstract']}".strip()
        chunks, sent_map = preprocess_document(raw_text)
        if len(chunks) != len(sent_map):
            print(f"⚠️ Warning: chunks and sent_map length mismatch for PMID {pmid}")
        metadata.extend([[pmid, cid, chunk] for cid, chunk in enumerate(chunks)])
        sentence_maps.extend(sent_map)

    index.add(embeddings)

else:
    all_chunks, all_metadata, all_sent_map = [], [], []

    for item in tqdm(dataset, desc="Preprocessing dataset"):
        pmid = int(item["PMID"])
        raw_text = f"{item['title']} {item['abstract']}".strip()
        chunks, sent_map = preprocess_document(raw_text)
        if len(chunks) != len(sent_map):
            print(f"⚠️ Warning: chunks and sent_map length mismatch for PMID {pmid}")
        for cid, chunk in enumerate(chunks):
            if not is_valid_chunk(chunk):
                continue
            all_chunks.append(chunk)
            all_metadata.append([pmid, cid, chunk])
            all_sent_map.append(sent_map[cid])

    print(f"📦 Encoding {len(all_chunks)} chunks in batches of {BATCH_SIZE}...")

    embeddings_batches = []
    for i in tqdm(range(0, len(all_chunks), BATCH_SIZE), desc="Encoding batches"):
        batch = all_chunks[i:i+BATCH_SIZE]
        emb_batch = encode_text_batch(batch)
        index.add(emb_batch)
        embeddings_batches.append(emb_batch)

    embeddings = np.vstack(embeddings_batches)  # تبدیل به یک آرایه کامل
    metadata = all_metadata
    sentence_maps = all_sent_map

    with open(EMBED_CACHE_PATH, "wb") as f:
        pickle.dump(embeddings, f)

print("✅ FAISS index built with caching and batch encoding")

# 7️⃣ Load Dataset & build FAISS index
print("📥 Loading PubMed dataset...")
dataset = load_dataset("slinusc/PubMedAbstractsSubset", split="train[:1000]")
print("✅ Dataset loaded")

index = faiss.IndexFlatL2(EMBED_DIM)
metadata, sentence_maps = [], []

if os.path.exists(EMBED_CACHE_PATH):
    print("📂 Loading cached embeddings...")
    with open(EMBED_CACHE_PATH,"rb") as f: embeddings = pickle.load(f)
    for i,item in enumerate(dataset):
        pmid = int(item["PMID"])
        raw_text = f"{item['title']} {item['abstract']}".strip()
        chunks, sent_map = preprocess_document(raw_text)
        metadata.extend([[pmid, cid, chunk] for cid, chunk in enumerate(chunks)])
        sentence_maps.extend(sent_map)
    index.add(embeddings)
else:
    all_chunks, all_metadata, all_sent_map = [], [], []
    for item in tqdm(dataset):
        pmid = int(item["PMID"])
        raw_text = f"{item['title']} {item['abstract']}".strip()
        chunks, sent_map = preprocess_document(raw_text)
        for cid, chunk in enumerate(chunks):
            if not is_valid_chunk(chunk): continue
            all_chunks.append(chunk)
            all_metadata.append([pmid, cid, chunk])
            all_sent_map.append(sent_map[cid])
    embeddings = encode_text_batch(all_chunks)
    index.add(embeddings)
    metadata = all_metadata
    sentence_maps = all_sent_map
    with open(EMBED_CACHE_PATH,"wb") as f: pickle.dump(embeddings,f)

print("✅ FAISS index built with caching")

# 8️⃣ User Profile (interactive)
user_profile = {"user_id":"user_001", "specialty":None, "intent_bias":{"treatment":1.2,"review":1.0,"diagnosis":1.1}, "clicked_pmids":[]}

def set_user_profile(user_id, specialty):
    user_profile["user_id"] = user_id
    user_profile["specialty"] = specialty

def log_interaction(user, pmid):
    user["clicked_pmids"].append(pmid)

def build_user_embedding(user):
    if not user["clicked_pmids"]: return None
    embs = []
    for pmid, _, text in metadata:
        if pmid in user["clicked_pmids"]:
            embs.append(encode_text_batch([text])[0])
    if embs:
        return np.mean(embs, axis=0)
    return None

# 9️⃣ Intent Classification
INTENT_KEYWORDS = {"treatment":["treat","therapy","drug","headache","pain"],
                   "diagnosis":["diagnosis","symptom","test"],
                   "review":["review","survey"],
                   "education":["guide","tutorial"]}

def classify_intent(query:str):
    q = query.lower()
    for intent,kws in INTENT_KEYWORDS.items():
        if any(k in q for k in kws): return intent
    return "education"

# 🔹 Entity Extraction + Graph
def extract_entities(text):
    doc = nlp(text)
    entities = [(ent.text, ent.label_) for ent in doc.ents]
    # Build simple co-occurrence graph
    G = nx.Graph()
    for e,_ in entities: G.add_node(e)
    for i in range(len(entities)):
        for j in range(i+1,len(entities)):
            G.add_edge(entities[i][0], entities[j][0])
    return entities, G

# 1️⃣0️⃣ Retrieval + Recommender scoring
def retrieve(query_emb,k=10):
    _, idxs = index.search(query_emb,k)
    return idxs[0]

def recommender_score(query, idx, intent, user_emb=None):
    rel_score = 1.0
    intent_weight = user_profile["intent_bias"].get(intent,1.0)
    pers_score = 1.0
    if user_emb is not None:
        item_emb = encode_text_batch([metadata[idx][2]])[0]
        pers_score += float(np.dot(user_emb, item_emb.T))
    query_entities,_ = extract_entities(query)
    doc_entities,_ = extract_entities(metadata[idx][2])
    kb_score = len(set([e[0] for e in doc_entities]) & set([e[0] for e in query_entities])) + 1
    return rel_score * intent_weight * pers_score * kb_score

def recommender_rerank(query, candidate_indices, user):
    intent = classify_intent(query)
    user_emb = build_user_embedding(user)
    scores = [recommender_score(query, idx, intent, user_emb) for idx in candidate_indices]
    ranked = np.argsort(scores)[::-1]
    return [candidate_indices[i] for i in ranked]

# 1️⃣1️⃣ Load Flan-T5-base
llm_tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
llm_model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base").to(DEVICE)

def call_llm(prompt):
    inputs = llm_tokenizer(prompt, return_tensors="pt", truncation=True, max_length=MAX_LLM_INPUT_TOKENS).to(DEVICE)
    with torch.no_grad():
        output = llm_model.generate(**inputs, max_new_tokens=MAX_LLM_OUTPUT_TOKENS)
    return llm_tokenizer.decode(output[0], skip_special_tokens=True)

# 1️⃣2️⃣ RAG + Explainability + PMIDs + Sentence-level
def search_and_explain(query, top_k_chunks=5):
    emb = encode_text_batch([preprocess_query(query)])[0:1]
    idxs = retrieve(emb, k=top_k_chunks*5)
    candidate_pmids = [metadata[i][0] for i in idxs]
    idxs_rerank = recommender_rerank(query, idxs, user_profile)[:top_k_chunks]
    topk_pmids = [metadata[i][0] for i in idxs_rerank]

    contexts, citations = [], []
    for i in idxs_rerank:
        log_interaction(user_profile, metadata[i][0])
        sentences = sentence_maps[i]
        for s in sentences:
            if any(w.lower() in s.lower() for w in query.lower().split()):
                contexts.append(s)
                citations.append(metadata[i][0])
                break

    context_text = ' '.join(contexts)[:MAX_LLM_INPUT_TOKENS]
    intent = classify_intent(query)
    prompt = f"""
You are explaining WHY the following articles were recommended
for a {intent} task. Use only the context below and provide citations.

Context:
{context_text}

Citations (PMID):
{', '.join(map(str,citations))}

Explain the recommendation.
"""
    explanation = call_llm(prompt)
    return explanation, candidate_pmids, topk_pmids

# 1️⃣3️⃣ Interactive GUI
query_box = widgets.Textarea(
    value='',
    placeholder='Enter your medical query...',
    description='Query:',
    layout=widgets.Layout(width='600px', height='80px')
)

topk_slider = widgets.IntSlider(
    value=5,
    min=1,
    max=10,
    step=1,
    description='Top-K:',
    layout=widgets.Layout(width='400px')
)

submit_button = widgets.Button(
    description='Get Recommendations',
    button_style='success',
    layout=widgets.Layout(width='250px')
)

output = widgets.Output(layout=widgets.Layout(width='900px'))

def on_submit_clicked(b):
    with output:
        clear_output()
        query = query_box.value.strip()
        top_k = topk_slider.value
        if not query:
            print("❌ Please enter a query.")
            return
        print("⏳ Processing...")

        explanation, candidate_pmids, topk_pmids = search_and_explain(query, top_k_chunks=top_k)

        print(f"\n📌 Candidate PMIDs (before rerank): {candidate_pmids}")
        print(f"✅ Top-{top_k} PMIDs (after rerank): {topk_pmids}\n")
        print("📄 Explanation by LLM:\n")
        print(explanation)

submit_button.on_click(on_submit_clicked)
display(query_box, topk_slider, submit_button, output)